# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.3.2
_src_path: gh:algorandfoundation/algokit-typescript-template
author_email: hilaal@gmail.com
author_name: Hilal Agil
contract_name: island_asset
preset_name: starter
project_name: boli-contracts

